# kibana.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.13.4
      env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
      ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
  - name: elastic
    port: 9200
    targetPort: 9200
  type: NodePort